### ISSUE TITLE
Typo Issue in LibreriaLedRGB/examples/en-defaultcolors/en-defaultcolors.ino

### ISSUE THREAD

**Issue by animeshsrivastava24** [alexbertis/LibreriaLedRGB#2]
Hi, I was going through your library. I found a code issue here: [LibreriaLedRGB/examples/en-defaultcolors/en-defaultcolors.ino](https://github.com/alexbertis/LibreriaLedRGB/blob/master/examples/en-defaultcolors/en-defaultcolors.ino)
Line 17: ~~my~~ to mi

**Comment by alexbertis** [comment]
Sorry, didn't check the translation. Releasing a fix rn! Version 1.0.1 should be ok.
